---
- name: Configure apache web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to httpd server installed by ansible</h1>"
