name: destroy infra
on: 
  workflow_dispatch:
jobs:
  destroy_infra:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: install terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: aws intergation using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::736218978384:role/github-oidc-full-perms
          aws-region: ap-south-1

      - name: get key_name
        run: ssh-keygen -t rsa -N "" -f "ec2_login_key"
        
      - name: initialize
        run: terraform init
        continue-on-error: true

      - name: plan_destroy
        id: plan
        run: terraform plan -destroy -out myplan
        continue-on-error: true

      - name: retry_plan #(on failure)
        if: steps.plan.outcome == 'failure'
        run: |
          echo "plan failed, retrying.."
          terraform plan -destroy -out myplan || terraform plan -destroy -out myplan
        continue-on-error: true

      - name: apply_destroy
        run: terraform apply myplan
        continue-on-error: true

      - name: Post-Deployment Outputs
        if: always()
        run: terraform output

      - name: Failure Notification
        if: failure()
        run: |
          echo "Terraform destroy Failed!"
          exit 1

          
    